import { Business, Category } from "./types";

export const CATEGORIES: Category[] = [
  "Todos",
  "Produtos Coloniais",
  "Serviços",
  "Gastronomia",
  "Utilidade",
  "Saúde",
  "Comércio",
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Venda de Ovos da Dona Maria",
    category: "Produtos Coloniais",
    location: "Bairro Alto, Águas Mornas",
    phone: "5548999990001",
    imageUrl: "https://picsum.photos/seed/ovos-coloniais/400/300",
    isOpen: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 48,
    description: "Ovos coloniais frescos, galinha caipira e produtos da roça.",
  },
  {
    id: "2",
    name: "Eletricista do Seu João",
    category: "Serviços",
    location: "Centro, Águas Mornas",
    phone: "5548999990002",
    imageUrl: "https://picsum.photos/seed/eletricista-joao/400/300",
    isOpen: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 73,
    description:
      "Instalações elétricas residenciais e comerciais. Atendimento rápido.",
  },
  {
    id: "3",
    name: "Padaria Central",
    category: "Gastronomia",
    location: "Centro, Águas Mornas",
    phone: "5548999990003",
    imageUrl: "https://picsum.photos/seed/padaria-central/400/300",
    isOpen: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 120,
    description:
      "Pão fresquinho, bolos artesanais, salgados e café da manhã completo.",
  },
  {
    id: "4",
    name: "Farmácia São José",
    category: "Saúde",
    location: "Centro, Águas Mornas",
    phone: "5548999990004",
    imageUrl: "https://picsum.photos/seed/farmacia-sao-jose/400/300",
    isOpen: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 95,
    description:
      "Medicamentos, cosméticos e atendimento farmacêutico personalizado.",
  },
  {
    id: "5",
    name: "Mercearia do Zé",
    category: "Comércio",
    location: "Vila Nova, Águas Mornas",
    phone: "5548999990005",
    imageUrl: "https://picsum.photos/seed/mercearia-ze/400/300",
    isOpen: false,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 31,
    description:
      "Produtos de primeira necessidade, frios, bebidas e hortifruti.",
  },
  {
    id: "6",
    name: "Salão da Margareth",
    category: "Serviços",
    location: "Bairro Novo, Águas Mornas",
    phone: "5548999990006",
    imageUrl: "https://picsum.photos/seed/salao-margareth/400/300",
    isOpen: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 57,
    description: "Corte, coloração, hidratação, manicure e pedicure.",
  },
  {
    id: "7",
    name: "Restaurante da Vó Lurdes",
    category: "Gastronomia",
    location: "Estrada do Campo, Águas Mornas",
    phone: "5548999990007",
    imageUrl: "https://picsum.photos/seed/restaurante-lurdes/400/300",
    isOpen: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 84,
    description:
      "Comida caseira colonial. Almoço de segunda a sábado. Porções generosas.",
  },
  {
    id: "8",
    name: "Pousada Vale Verde",
    category: "Utilidade",
    location: "Linha São Luís, Águas Mornas",
    phone: "5548999990008",
    imageUrl: "https://picsum.photos/seed/pousada-vale/400/300",
    isOpen: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 29,
    description:
      "Hospedagem aconchegante em meio à natureza. Café da manhã incluso.",
  },
  {
    id: "9",
    name: "Borracharia e Pneus do Mário",
    category: "Serviços",
    location: "Entrada da Cidade, Águas Mornas",
    phone: "5548999990009",
    imageUrl: "https://picsum.photos/seed/borracharia-mario/400/300",
    isOpen: false,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 18,
    description:
      "Troca de pneus, balanceamento, alinhamento e borracharia em geral.",
  },
  {
    id: "10",
    name: "Feira Orgânica do Sábado",
    category: "Produtos Coloniais",
    location: "Praça Central, Águas Mornas",
    phone: "5548999990010",
    imageUrl: "https://picsum.photos/seed/feira-organica/400/300",
    isOpen: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 63,
    description: "Frutas, verduras orgânicas e produtos coloniais toda semana.",
  },
];
