import { Business, Category } from "./types";

/** Chips sempre visíveis na barra horizontal de filtros */
export const PRIMARY_CATEGORIES: Category[] = [
  "Todos",
  "Produtos Coloniais",
  "Gastronomia",
  "Serviços",
  "Casa",
  "Moda & Beleza",
  "Saúde",
];

/** Categorias agrupadas no botão "Mais" */
export const EXTRA_CATEGORIES: Category[] = [
  "Carro",
  "Construção",

  "Educação",
  "Turismo",
  "Agropecuária",
  "Comércio",
  "Utilidade",
];

/** Lista completa — usada na lógica de filtragem */
export const CATEGORIES: Category[] = [
  ...PRIMARY_CATEGORIES.filter((c) => c !== "Todos"),
  ...EXTRA_CATEGORIES,
] as Category[];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "1",
    slug: "venda-de-ovos-dona-maria",
    businessName: "Venda de Ovos da Dona Maria",
    category: "Produtos Coloniais",
    location: "Bairro Alto, Águas Mornas",
    address: {
      street: "Estrada Geral do Bairro Alto, 145, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990001",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Estrada+Geral+do+Bairro+Alto+145+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/ovos-coloniais/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-ovos-dona-maria/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-ovos-dona-maria/200/200",
    galleryImages: [
      "https://picsum.photos/seed/ovos-galeria-1/400/300",
      "https://picsum.photos/seed/ovos-galeria-2/400/300",
      "https://picsum.photos/seed/ovos-galeria-3/400/300",
      "https://picsum.photos/seed/ovos-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 48,
    description:
      "Produção familiar de ovos coloniais, frango caipira e derivados frescos da roça com entrega em Águas Mornas.",
    workingHours: [
      "Segunda a Sexta: 07:00 - 18:00",
      "Sábado: 07:00 - 14:00",
      "Domingo: Fechado",
    ],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Débito"],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "2",
    slug: "eletricista-seu-joao",
    businessName: "Eletricista do Seu João",
    category: "Serviços",
    location: "Centro, Águas Mornas",
    address: {
      street: "Rua das Araucárias, 82, Centro, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990002",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Rua+das+Araucarias+82+Centro+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/eletricista-joao/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-eletricista-joao/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-eletricista-joao/200/200",
    galleryImages: [
      "https://picsum.photos/seed/joao-galeria-1/400/300",
      "https://picsum.photos/seed/joao-galeria-2/400/300",
      "https://picsum.photos/seed/joao-galeria-3/400/300",
      "https://picsum.photos/seed/joao-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 73,
    description:
      "Instalações elétricas residenciais e comerciais, manutenção preventiva e atendimento emergencial no município.",
    workingHours: [
      "Segunda a Sexta: 08:00 - 19:00",
      "Sábado: 08:00 - 13:00",
      "Domingo: Plantão por WhatsApp",
    ],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Crédito"],
    hasParking: false,
    hasDelivery: false,
  },
  {
    id: "3",
    slug: "padaria-central",
    businessName: "Padaria Central",
    category: "Gastronomia",
    location: "Centro, Águas Mornas",
    address: {
      street: "Avenida Principal, 201, Centro, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990003",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Avenida+Principal+201+Centro+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/padaria-central/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-padaria-central/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-padaria-central/200/200",
    galleryImages: [
      "https://picsum.photos/seed/padaria-galeria-1/400/300",
      "https://picsum.photos/seed/padaria-galeria-2/400/300",
      "https://picsum.photos/seed/padaria-galeria-3/400/300",
      "https://picsum.photos/seed/padaria-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 120,
    description:
      "Padaria tradicional da cidade com pães frescos, bolos artesanais, café colonial e encomendas para eventos.",
    workingHours: ["Segunda a Sábado: 06:00 - 20:00", "Domingo: 06:30 - 12:30"],
    paymentMethods: [
      "Pix",
      "Dinheiro",
      "Cartão de Débito",
      "Cartão de Crédito",
    ],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "4",
    slug: "farmacia-sao-jose",
    businessName: "Farmácia São José",
    category: "Saúde",
    location: "Centro, Águas Mornas",
    address: {
      street: "Rua da Igreja, 50, Centro, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990004",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Rua+da+Igreja+50+Centro+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/farmacia-sao-jose/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-farmacia-sao-jose/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-farmacia-sao-jose/200/200",
    galleryImages: [
      "https://picsum.photos/seed/farmacia-galeria-1/400/300",
      "https://picsum.photos/seed/farmacia-galeria-2/400/300",
      "https://picsum.photos/seed/farmacia-galeria-3/400/300",
      "https://picsum.photos/seed/farmacia-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 95,
    description:
      "Medicamentos, produtos de higiene, perfumaria e atendimento farmacêutico com foco em cuidado comunitário.",
    workingHours: [
      "Segunda a Sexta: 08:00 - 22:00",
      "Sábado: 08:00 - 20:00",
      "Domingo: 09:00 - 13:00",
    ],
    paymentMethods: [
      "Pix",
      "Dinheiro",
      "Cartão de Débito",
      "Cartão de Crédito",
    ],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "5",
    slug: "mercearia-do-ze",
    businessName: "Mercearia do Zé",
    category: "Comércio",
    location: "Vila Nova, Águas Mornas",
    address: {
      street: "Rua da Ponte, 312, Vila Nova, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990005",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Rua+da+Ponte+312+Vila+Nova+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/mercearia-ze/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-mercearia-ze/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-mercearia-ze/200/200",
    galleryImages: [
      "https://picsum.photos/seed/mercearia-galeria-1/400/300",
      "https://picsum.photos/seed/mercearia-galeria-2/400/300",
      "https://picsum.photos/seed/mercearia-galeria-3/400/300",
      "https://picsum.photos/seed/mercearia-galeria-4/400/300",
    ],
    isOpen: false,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 31,
    description:
      "Mercearia de bairro com itens essenciais, bebidas geladas, frios e entrega local na Vila Nova.",
    workingHours: [
      "Segunda a Sexta: 08:00 - 19:00",
      "Sábado: 08:00 - 17:00",
      "Domingo: Fechado",
    ],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Débito"],
    hasParking: false,
    hasDelivery: true,
  },
  {
    id: "6",
    slug: "salao-da-margareth",
    businessName: "Salão da Margareth",
    category: "Serviços",
    location: "Bairro Novo, Águas Mornas",
    address: {
      street: "Rua das Flores, 97, Bairro Novo, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990006",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Rua+das+Flores+97+Bairro+Novo+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/salao-margareth/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-salao-margareth/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-salao-margareth/200/200",
    galleryImages: [
      "https://picsum.photos/seed/salao-galeria-1/400/300",
      "https://picsum.photos/seed/salao-galeria-2/400/300",
      "https://picsum.photos/seed/salao-galeria-3/400/300",
      "https://picsum.photos/seed/salao-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 57,
    description:
      "Beleza e autocuidado com corte, coloração, manicure e atendimento com horário agendado.",
    workingHours: [
      "Terça a Sexta: 09:00 - 19:00",
      "Sábado: 08:30 - 16:00",
      "Domingo e Segunda: Fechado",
    ],
    paymentMethods: [
      "Pix",
      "Dinheiro",
      "Cartão de Débito",
      "Cartão de Crédito",
    ],
    hasParking: true,
    hasDelivery: true,
  },
  {
    id: "7",
    slug: "restaurante-vo-lurdes",
    businessName: "Restaurante da Vó Lurdes",
    category: "Gastronomia",
    location: "Estrada do Campo, Águas Mornas",
    address: {
      street: "Estrada do Campo, km 3, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990007",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Estrada+do+Campo+km+3+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/restaurante-lurdes/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-restaurante-lurdes/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-restaurante-lurdes/200/200",
    galleryImages: [
      "https://picsum.photos/seed/restaurante-galeria-1/400/300",
      "https://picsum.photos/seed/restaurante-galeria-2/400/300",
      "https://picsum.photos/seed/restaurante-galeria-3/400/300",
      "https://picsum.photos/seed/restaurante-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 84,
    description:
      "Restaurante colonial com buffet caseiro e receitas tradicionais da região serrana.",
    workingHours: ["Segunda a Sábado: 11:00 - 15:00", "Domingo: Fechado"],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Débito"],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "8",
    slug: "pousada-vale-verde",
    businessName: "Pousada Vale Verde",
    category: "Utilidade",
    location: "Linha São Luís, Águas Mornas",
    address: {
      street: "Linha São Luís, 450, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990008",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Linha+Sao+Luis+450+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/pousada-vale/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-pousada-vale/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-pousada-vale/200/200",
    galleryImages: [
      "https://picsum.photos/seed/pousada-galeria-1/400/300",
      "https://picsum.photos/seed/pousada-galeria-2/400/300",
      "https://picsum.photos/seed/pousada-galeria-3/400/300",
      "https://picsum.photos/seed/pousada-galeria-4/400/300",
    ],
    isOpen: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 29,
    description:
      "Hospedagem acolhedora em área verde, ideal para descanso e turismo rural na região.",
    workingHours: ["Atendimento diário: 07:00 - 22:00"],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Crédito"],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "9",
    slug: "borracharia-pneus-mario",
    businessName: "Borracharia e Pneus do Mário",
    category: "Serviços",
    location: "Entrada da Cidade, Águas Mornas",
    address: {
      street: "SC-435, 20, Entrada da Cidade, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990009",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=SC-435+20+Entrada+da+Cidade+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/borracharia-mario/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-borracharia-mario/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-borracharia-mario/200/200",
    galleryImages: [
      "https://picsum.photos/seed/borracharia-galeria-1/400/300",
      "https://picsum.photos/seed/borracharia-galeria-2/400/300",
      "https://picsum.photos/seed/borracharia-galeria-3/400/300",
      "https://picsum.photos/seed/borracharia-galeria-4/400/300",
    ],
    isOpen: false,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 18,
    description:
      "Serviços de borracharia, troca e reparo de pneus para carros, motos e utilitários.",
    workingHours: [
      "Segunda a Sexta: 08:00 - 18:00",
      "Sábado: 08:00 - 12:00",
      "Domingo: Fechado",
    ],
    paymentMethods: ["Pix", "Dinheiro", "Cartão de Débito"],
    hasParking: true,
    hasDelivery: false,
  },
  {
    id: "10",
    slug: "feira-organica-sabado",
    businessName: "Feira Orgânica do Sábado",
    category: "Produtos Coloniais",
    location: "Praça Central, Águas Mornas",
    address: {
      street: "Praça Central, Centro, Águas Mornas - SC",
      city: "Águas Mornas",
      state: "SC",
    },
    businessWhatsapp: "5548999990010",
    mapUrl:
      "https://www.google.com/maps/search/?api=1&query=Praca+Central+Centro+Aguas+Mornas+SC",
    avatar: "https://picsum.photos/seed/feira-organica/400/300",
    bannerUrl: "https://picsum.photos/seed/banner-feira-organica/1200/500",
    logoUrl: "https://picsum.photos/seed/logo-feira-organica/200/200",
    galleryImages: [
      "https://picsum.photos/seed/feira-galeria-1/400/300",
      "https://picsum.photos/seed/feira-galeria-2/400/300",
      "https://picsum.photos/seed/feira-galeria-3/400/300",
      "https://picsum.photos/seed/feira-galeria-4/400/300",
    ],
    isOpen: false,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 63,
    description:
      "Feira semanal com alimentos orgânicos, produtos coloniais e contato direto com produtores locais.",
    workingHours: ["Sábado: 07:00 - 12:30"],
    paymentMethods: ["Pix", "Dinheiro"],
    hasParking: false,
    hasDelivery: false,
  },
];

export function getBusinessBySlug(slug: string): Business | undefined {
  return MOCK_BUSINESSES.find((business) => business.slug === slug);
}
